[package]
name = "tf-assets"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Packs de ressources : blockstates → modèles → textures, sans jamais rien redistribuer"

[dependencies]
tf-anvil.workspace = true
tf-mesh.workspace = true
flate2.workspace = true
serde_json = "1"
png = "0.17"

[dev-dependencies]
tf-bench = { path = "../tf-bench" }
